# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ieee80211ah_swig', [dirname(__file__)])
        except ImportError:
            import _ieee80211ah_swig
            return _ieee80211ah_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_ieee80211ah_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ieee80211ah_swig = swig_import_helper()
    del swig_import_helper
else:
    import _ieee80211ah_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _ieee80211ah_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _ieee80211ah_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _ieee80211ah_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _ieee80211ah_swig.high_res_timer_epoch()
class ah_chunks_to_symbols(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """
        make() -> ah_chunks_to_symbols_sptr

        Params: (NONE)
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_make()

    make = staticmethod(make)
    __swig_destroy__ = _ieee80211ah_swig.delete_ah_chunks_to_symbols
    __del__ = lambda self : None;
ah_chunks_to_symbols_swigregister = _ieee80211ah_swig.ah_chunks_to_symbols_swigregister
ah_chunks_to_symbols_swigregister(ah_chunks_to_symbols)

def ah_chunks_to_symbols_make():
  """
    ah_chunks_to_symbols_make() -> ah_chunks_to_symbols_sptr

    Params: (NONE)
    """
  return _ieee80211ah_swig.ah_chunks_to_symbols_make()

class ah_chunks_to_symbols_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::ieee80211ah::ah_chunks_to_symbols)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::ieee80211ah::ah_chunks_to_symbols)> self) -> ah_chunks_to_symbols_sptr
        __init__(boost::shared_ptr<(gr::ieee80211ah::ah_chunks_to_symbols)> self, ah_chunks_to_symbols p) -> ah_chunks_to_symbols_sptr
        """
        this = _ieee80211ah_swig.new_ah_chunks_to_symbols_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(ah_chunks_to_symbols_sptr self) -> ah_chunks_to_symbols"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr___deref__(self)

    __swig_destroy__ = _ieee80211ah_swig.delete_ah_chunks_to_symbols_sptr
    __del__ = lambda self : None;
    def make(self):
        """
        make(ah_chunks_to_symbols_sptr self) -> ah_chunks_to_symbols_sptr

        Params: (NONE)
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_make(self)

    def history(self):
        """history(ah_chunks_to_symbols_sptr self) -> unsigned int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(ah_chunks_to_symbols_sptr self, int which, int delay)
        declare_sample_delay(ah_chunks_to_symbols_sptr self, unsigned int delay)
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(ah_chunks_to_symbols_sptr self, int which) -> unsigned int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(ah_chunks_to_symbols_sptr self) -> int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(ah_chunks_to_symbols_sptr self) -> double"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_relative_rate(self)

    def start(self):
        """start(ah_chunks_to_symbols_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_start(self)

    def stop(self):
        """stop(ah_chunks_to_symbols_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(ah_chunks_to_symbols_sptr self, unsigned int which_input) -> uint64_t"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(ah_chunks_to_symbols_sptr self, unsigned int which_output) -> uint64_t"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(ah_chunks_to_symbols_sptr self) -> int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(ah_chunks_to_symbols_sptr self, int m)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(ah_chunks_to_symbols_sptr self)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(ah_chunks_to_symbols_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(ah_chunks_to_symbols_sptr self, int m)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(ah_chunks_to_symbols_sptr self) -> int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(ah_chunks_to_symbols_sptr self, int i) -> long"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(ah_chunks_to_symbols_sptr self, long max_output_buffer)
        set_max_output_buffer(ah_chunks_to_symbols_sptr self, int port, long max_output_buffer)
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(ah_chunks_to_symbols_sptr self, int i) -> long"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(ah_chunks_to_symbols_sptr self, long min_output_buffer)
        set_min_output_buffer(ah_chunks_to_symbols_sptr self, int port, long min_output_buffer)
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(ah_chunks_to_symbols_sptr self, int which) -> float
        pc_input_buffers_full(ah_chunks_to_symbols_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(ah_chunks_to_symbols_sptr self, int which) -> float
        pc_input_buffers_full_avg(ah_chunks_to_symbols_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(ah_chunks_to_symbols_sptr self, int which) -> float
        pc_input_buffers_full_var(ah_chunks_to_symbols_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(ah_chunks_to_symbols_sptr self, int which) -> float
        pc_output_buffers_full(ah_chunks_to_symbols_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(ah_chunks_to_symbols_sptr self, int which) -> float
        pc_output_buffers_full_avg(ah_chunks_to_symbols_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(ah_chunks_to_symbols_sptr self, int which) -> float
        pc_output_buffers_full_var(ah_chunks_to_symbols_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(ah_chunks_to_symbols_sptr self) -> float"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(ah_chunks_to_symbols_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(ah_chunks_to_symbols_sptr self)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(ah_chunks_to_symbols_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(ah_chunks_to_symbols_sptr self) -> int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(ah_chunks_to_symbols_sptr self) -> int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(ah_chunks_to_symbols_sptr self, int priority) -> int"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(ah_chunks_to_symbols_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_name(self)

    def symbol_name(self):
        """symbol_name(ah_chunks_to_symbols_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(ah_chunks_to_symbols_sptr self) -> io_signature_sptr"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(ah_chunks_to_symbols_sptr self) -> io_signature_sptr"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(ah_chunks_to_symbols_sptr self) -> long"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(ah_chunks_to_symbols_sptr self) -> basic_block_sptr"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(ah_chunks_to_symbols_sptr self, int ninputs, int noutputs) -> bool"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(ah_chunks_to_symbols_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(ah_chunks_to_symbols_sptr self, std::string name)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(ah_chunks_to_symbols_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(ah_chunks_to_symbols_sptr self) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(ah_chunks_to_symbols_sptr self) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(ah_chunks_to_symbols_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_chunks_to_symbols_sptr_message_subscribers(self, *args, **kwargs)

ah_chunks_to_symbols_sptr_swigregister = _ieee80211ah_swig.ah_chunks_to_symbols_sptr_swigregister
ah_chunks_to_symbols_sptr_swigregister(ah_chunks_to_symbols_sptr)

ah_chunks_to_symbols_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
ah_chunks_to_symbols = ah_chunks_to_symbols.make;

BPSK_1_2 = _ieee80211ah_swig.BPSK_1_2
QPSK_1_2 = _ieee80211ah_swig.QPSK_1_2
QPSK_3_4 = _ieee80211ah_swig.QPSK_3_4
QAM16_1_2 = _ieee80211ah_swig.QAM16_1_2
QAM16_3_4 = _ieee80211ah_swig.QAM16_3_4
QAM64_2_3 = _ieee80211ah_swig.QAM64_2_3
QAM64_3_4 = _ieee80211ah_swig.QAM64_3_4
QAM64_5_6 = _ieee80211ah_swig.QAM64_5_6
QAM256_3_4 = _ieee80211ah_swig.QAM256_3_4
class ah_ofdm_mapper(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def make(*args, **kwargs):
        """
        make(Encoding mcs, bool debug=False) -> ah_ofdm_mapper_sptr

        Params: (mcs, debug)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_make(*args, **kwargs)

    make = staticmethod(make)
    def set_encoding_ah(self, *args, **kwargs):
        """
        set_encoding_ah(ah_ofdm_mapper self, Encoding encoding)

        Params: (encoding)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_set_encoding_ah(self, *args, **kwargs)

    __swig_destroy__ = _ieee80211ah_swig.delete_ah_ofdm_mapper
    __del__ = lambda self : None;
ah_ofdm_mapper_swigregister = _ieee80211ah_swig.ah_ofdm_mapper_swigregister
ah_ofdm_mapper_swigregister(ah_ofdm_mapper)

def ah_ofdm_mapper_make(*args, **kwargs):
  """
    ah_ofdm_mapper_make(Encoding mcs, bool debug=False) -> ah_ofdm_mapper_sptr

    Params: (mcs, debug)
    """
  return _ieee80211ah_swig.ah_ofdm_mapper_make(*args, **kwargs)

class ah_ofdm_mapper_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::ieee80211ah::ah_ofdm_mapper)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::ieee80211ah::ah_ofdm_mapper)> self) -> ah_ofdm_mapper_sptr
        __init__(boost::shared_ptr<(gr::ieee80211ah::ah_ofdm_mapper)> self, ah_ofdm_mapper p) -> ah_ofdm_mapper_sptr
        """
        this = _ieee80211ah_swig.new_ah_ofdm_mapper_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(ah_ofdm_mapper_sptr self) -> ah_ofdm_mapper"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr___deref__(self)

    __swig_destroy__ = _ieee80211ah_swig.delete_ah_ofdm_mapper_sptr
    __del__ = lambda self : None;
    def make(self, *args, **kwargs):
        """
        make(ah_ofdm_mapper_sptr self, Encoding mcs, bool debug=False) -> ah_ofdm_mapper_sptr

        Params: (mcs, debug)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_make(self, *args, **kwargs)

    def set_encoding_ah(self, *args, **kwargs):
        """
        set_encoding_ah(ah_ofdm_mapper_sptr self, Encoding encoding)

        Params: (encoding)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_encoding_ah(self, *args, **kwargs)

    def history(self):
        """history(ah_ofdm_mapper_sptr self) -> unsigned int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(ah_ofdm_mapper_sptr self, int which, int delay)
        declare_sample_delay(ah_ofdm_mapper_sptr self, unsigned int delay)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(ah_ofdm_mapper_sptr self, int which) -> unsigned int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(ah_ofdm_mapper_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(ah_ofdm_mapper_sptr self) -> double"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_relative_rate(self)

    def start(self):
        """start(ah_ofdm_mapper_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_start(self)

    def stop(self):
        """stop(ah_ofdm_mapper_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(ah_ofdm_mapper_sptr self, unsigned int which_input) -> uint64_t"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(ah_ofdm_mapper_sptr self, unsigned int which_output) -> uint64_t"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(ah_ofdm_mapper_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(ah_ofdm_mapper_sptr self, int m)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(ah_ofdm_mapper_sptr self)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(ah_ofdm_mapper_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(ah_ofdm_mapper_sptr self, int m)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(ah_ofdm_mapper_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(ah_ofdm_mapper_sptr self, int i) -> long"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(ah_ofdm_mapper_sptr self, long max_output_buffer)
        set_max_output_buffer(ah_ofdm_mapper_sptr self, int port, long max_output_buffer)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(ah_ofdm_mapper_sptr self, int i) -> long"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(ah_ofdm_mapper_sptr self, long min_output_buffer)
        set_min_output_buffer(ah_ofdm_mapper_sptr self, int port, long min_output_buffer)
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(ah_ofdm_mapper_sptr self, int which) -> float
        pc_input_buffers_full(ah_ofdm_mapper_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(ah_ofdm_mapper_sptr self, int which) -> float
        pc_input_buffers_full_avg(ah_ofdm_mapper_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(ah_ofdm_mapper_sptr self, int which) -> float
        pc_input_buffers_full_var(ah_ofdm_mapper_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(ah_ofdm_mapper_sptr self, int which) -> float
        pc_output_buffers_full(ah_ofdm_mapper_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(ah_ofdm_mapper_sptr self, int which) -> float
        pc_output_buffers_full_avg(ah_ofdm_mapper_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(ah_ofdm_mapper_sptr self, int which) -> float
        pc_output_buffers_full_var(ah_ofdm_mapper_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(ah_ofdm_mapper_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(ah_ofdm_mapper_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(ah_ofdm_mapper_sptr self)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(ah_ofdm_mapper_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(ah_ofdm_mapper_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(ah_ofdm_mapper_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(ah_ofdm_mapper_sptr self, int priority) -> int"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(ah_ofdm_mapper_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_name(self)

    def symbol_name(self):
        """symbol_name(ah_ofdm_mapper_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(ah_ofdm_mapper_sptr self) -> io_signature_sptr"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(ah_ofdm_mapper_sptr self) -> io_signature_sptr"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(ah_ofdm_mapper_sptr self) -> long"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(ah_ofdm_mapper_sptr self) -> basic_block_sptr"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(ah_ofdm_mapper_sptr self, int ninputs, int noutputs) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(ah_ofdm_mapper_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(ah_ofdm_mapper_sptr self, std::string name)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(ah_ofdm_mapper_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(ah_ofdm_mapper_sptr self) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(ah_ofdm_mapper_sptr self) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(ah_ofdm_mapper_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_ofdm_mapper_sptr_message_subscribers(self, *args, **kwargs)

ah_ofdm_mapper_sptr_swigregister = _ieee80211ah_swig.ah_ofdm_mapper_sptr_swigregister
ah_ofdm_mapper_sptr_swigregister(ah_ofdm_mapper_sptr)

ah_ofdm_mapper_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
ah_ofdm_mapper = ah_ofdm_mapper.make;

class ah_ofdm_decode_mac(object):
    """Proxy of C++ gr::ieee80211ah::ah_ofdm_decode_mac class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make(log=False, debug=False):
        """make(bool log=False, bool debug=False) -> ah_ofdm_decode_mac_sptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_make(log, debug)

    make = staticmethod(make)
    __swig_destroy__ = _ieee80211ah_swig.delete_ah_ofdm_decode_mac
    __del__ = lambda self : None;
ah_ofdm_decode_mac_swigregister = _ieee80211ah_swig.ah_ofdm_decode_mac_swigregister
ah_ofdm_decode_mac_swigregister(ah_ofdm_decode_mac)

def ah_ofdm_decode_mac_make(log=False, debug=False):
  """ah_ofdm_decode_mac_make(bool log=False, bool debug=False) -> ah_ofdm_decode_mac_sptr"""
  return _ieee80211ah_swig.ah_ofdm_decode_mac_make(log, debug)

class ah_ofdm_decode_mac_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::ieee80211ah::ah_ofdm_decode_mac)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::ieee80211ah::ah_ofdm_decode_mac)> self) -> ah_ofdm_decode_mac_sptr
        __init__(boost::shared_ptr<(gr::ieee80211ah::ah_ofdm_decode_mac)> self, ah_ofdm_decode_mac p) -> ah_ofdm_decode_mac_sptr
        """
        this = _ieee80211ah_swig.new_ah_ofdm_decode_mac_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(ah_ofdm_decode_mac_sptr self) -> ah_ofdm_decode_mac"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr___deref__(self)

    __swig_destroy__ = _ieee80211ah_swig.delete_ah_ofdm_decode_mac_sptr
    __del__ = lambda self : None;
    def make(self, log=False, debug=False):
        """make(ah_ofdm_decode_mac_sptr self, bool log=False, bool debug=False) -> ah_ofdm_decode_mac_sptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_make(self, log, debug)

    def history(self):
        """history(ah_ofdm_decode_mac_sptr self) -> unsigned int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(ah_ofdm_decode_mac_sptr self, int which, int delay)
        declare_sample_delay(ah_ofdm_decode_mac_sptr self, unsigned int delay)
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(ah_ofdm_decode_mac_sptr self, int which) -> unsigned int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(ah_ofdm_decode_mac_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(ah_ofdm_decode_mac_sptr self) -> double"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_relative_rate(self)

    def start(self):
        """start(ah_ofdm_decode_mac_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_start(self)

    def stop(self):
        """stop(ah_ofdm_decode_mac_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(ah_ofdm_decode_mac_sptr self, unsigned int which_input) -> uint64_t"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(ah_ofdm_decode_mac_sptr self, unsigned int which_output) -> uint64_t"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(ah_ofdm_decode_mac_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(ah_ofdm_decode_mac_sptr self, int m)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(ah_ofdm_decode_mac_sptr self)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(ah_ofdm_decode_mac_sptr self) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(ah_ofdm_decode_mac_sptr self, int m)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(ah_ofdm_decode_mac_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(ah_ofdm_decode_mac_sptr self, int i) -> long"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(ah_ofdm_decode_mac_sptr self, long max_output_buffer)
        set_max_output_buffer(ah_ofdm_decode_mac_sptr self, int port, long max_output_buffer)
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(ah_ofdm_decode_mac_sptr self, int i) -> long"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(ah_ofdm_decode_mac_sptr self, long min_output_buffer)
        set_min_output_buffer(ah_ofdm_decode_mac_sptr self, int port, long min_output_buffer)
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(ah_ofdm_decode_mac_sptr self, int which) -> float
        pc_input_buffers_full(ah_ofdm_decode_mac_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(ah_ofdm_decode_mac_sptr self, int which) -> float
        pc_input_buffers_full_avg(ah_ofdm_decode_mac_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(ah_ofdm_decode_mac_sptr self, int which) -> float
        pc_input_buffers_full_var(ah_ofdm_decode_mac_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(ah_ofdm_decode_mac_sptr self, int which) -> float
        pc_output_buffers_full(ah_ofdm_decode_mac_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(ah_ofdm_decode_mac_sptr self, int which) -> float
        pc_output_buffers_full_avg(ah_ofdm_decode_mac_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(ah_ofdm_decode_mac_sptr self, int which) -> float
        pc_output_buffers_full_var(ah_ofdm_decode_mac_sptr self) -> pmt_vector_float
        """
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(ah_ofdm_decode_mac_sptr self) -> float"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(ah_ofdm_decode_mac_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(ah_ofdm_decode_mac_sptr self)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(ah_ofdm_decode_mac_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(ah_ofdm_decode_mac_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(ah_ofdm_decode_mac_sptr self) -> int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(ah_ofdm_decode_mac_sptr self, int priority) -> int"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(ah_ofdm_decode_mac_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_name(self)

    def symbol_name(self):
        """symbol_name(ah_ofdm_decode_mac_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(ah_ofdm_decode_mac_sptr self) -> io_signature_sptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(ah_ofdm_decode_mac_sptr self) -> io_signature_sptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(ah_ofdm_decode_mac_sptr self) -> long"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(ah_ofdm_decode_mac_sptr self) -> basic_block_sptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(ah_ofdm_decode_mac_sptr self, int ninputs, int noutputs) -> bool"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(ah_ofdm_decode_mac_sptr self) -> std::string"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(ah_ofdm_decode_mac_sptr self, std::string name)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(ah_ofdm_decode_mac_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(ah_ofdm_decode_mac_sptr self) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(ah_ofdm_decode_mac_sptr self) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(ah_ofdm_decode_mac_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_message_subscribers(self, *args, **kwargs)

ah_ofdm_decode_mac_sptr_swigregister = _ieee80211ah_swig.ah_ofdm_decode_mac_sptr_swigregister
ah_ofdm_decode_mac_sptr_swigregister(ah_ofdm_decode_mac_sptr)

ah_ofdm_decode_mac_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
ah_ofdm_decode_mac = ah_ofdm_decode_mac.make;



