INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_IEEE80211AH ieee80211ah)

FIND_PATH(
    IEEE80211AH_INCLUDE_DIRS
    NAMES ieee80211ah/api.h
    HINTS $ENV{IEEE80211AH_DIR}/include
        ${PC_IEEE80211AH_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    IEEE80211AH_LIBRARIES
    NAMES gnuradio-ieee80211ah
    HINTS $ENV{IEEE80211AH_DIR}/lib
        ${PC_IEEE80211AH_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IEEE80211AH DEFAULT_MSG IEEE80211AH_LIBRARIES IEEE80211AH_INCLUDE_DIRS)
MARK_AS_ADVANCED(IEEE80211AH_LIBRARIES IEEE80211AH_INCLUDE_DIRS)

